function out=chicken(a,b,c,FA)
  out=(-FA^3*(FA*(a+b)+4)*c^4 ...
     -4*FA^2*(FA*(a+b)+3)*c^3 ...
    -12*FA^1*(FA*(a+b)+2)*c^2 ...
    +24*(expl(1,FA*c)-FA*(a+b))*c ...
    +24*expl(1,FA*c)*(a+b))/(24*c^5);
end